# ...existing code...

ALLOWED_HOSTS = [
    'parking-management-system-sui2.onrender.com',
    # Add any other hosts you need
]

# ...existing code...

INSTALLED_APPS = [
    # ...existing apps...
    'widget_tweaks',
    # ...existing apps...
]

# ...existing code...