# ...existing code...
ALLOWED_HOSTS = [
    # ...existing hosts...
    'parking-management-system-sui2.onrender.com',
    # ...existing hosts...
]
# ...existing code...
INSTALLED_APPS = [
    # ...existing apps...
    'widget_tweaks',
    # ...existing apps...
]
# ...existing code...
